// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUyEVfb4EuNt9H651XEFjsAWm9VD3Ukv0',
    appId: '1:982139979037:web:971612b69fb42408780df4',
    messagingSenderId: '982139979037',
    projectId: 'pharmaconnect-d10e8',
    authDomain: 'pharmaconnect-d10e8.firebaseapp.com',
    databaseURL: 'https://pharmaconnect-d10e8-default-rtdb.firebaseio.com',
    storageBucket: 'pharmaconnect-d10e8.appspot.com',
    measurementId: 'G-56Y5RFXRYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKCONq1zdKVYJNCV4CFIyFu3nuz1KuJY4',
    appId: '1:982139979037:android:72d15748609a36a4780df4',
    messagingSenderId: '982139979037',
    projectId: 'pharmaconnect-d10e8',
    databaseURL: 'https://pharmaconnect-d10e8-default-rtdb.firebaseio.com',
    storageBucket: 'pharmaconnect-d10e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6KJ21AjgsVDYBi_V2Wx9hjrIxLrsVDWY',
    appId: '1:982139979037:ios:8c5ec155115ab5eb780df4',
    messagingSenderId: '982139979037',
    projectId: 'pharmaconnect-d10e8',
    databaseURL: 'https://pharmaconnect-d10e8-default-rtdb.firebaseio.com',
    storageBucket: 'pharmaconnect-d10e8.appspot.com',
    iosBundleId: 'com.example.pharmaConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6KJ21AjgsVDYBi_V2Wx9hjrIxLrsVDWY',
    appId: '1:982139979037:ios:8c5ec155115ab5eb780df4',
    messagingSenderId: '982139979037',
    projectId: 'pharmaconnect-d10e8',
    databaseURL: 'https://pharmaconnect-d10e8-default-rtdb.firebaseio.com',
    storageBucket: 'pharmaconnect-d10e8.appspot.com',
    iosBundleId: 'com.example.pharmaConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUyEVfb4EuNt9H651XEFjsAWm9VD3Ukv0',
    appId: '1:982139979037:web:63e21ccd880ca7b4780df4',
    messagingSenderId: '982139979037',
    projectId: 'pharmaconnect-d10e8',
    authDomain: 'pharmaconnect-d10e8.firebaseapp.com',
    databaseURL: 'https://pharmaconnect-d10e8-default-rtdb.firebaseio.com',
    storageBucket: 'pharmaconnect-d10e8.appspot.com',
    measurementId: 'G-E7H664001X',
  );

}